import './globals.css';

import store from '@/redux/store';
import Providers from '@/redux/Providers';
import Navbar from '@/components/Shared/Navbar';

// export const metadata = {
//    title: 'Watch Gallery',
//    description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
   return (
      <html lang='en' data-theme='light'>
         <body>
            <div>
               <Providers store={store}>
                  <Navbar />
                  {children}
               </Providers>
            </div>
         </body>
      </html>
   );
}
